ARG LANG=de_DE.UTF-8
ARG LANGUAGE=de_DE:de
ARG LC_ALL=de_DE.UTF-8
ARG TZ=Europe/Berlin
ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
LABEL org.opencontainers.image.authors="DerSni <31524614+DjSni@users.noreply.github.com>"
LABEL org.opencontainers.image.source="https://github.com/DjSni/kasm-images"
USER root

ENV HOME=/home/kasm-default-profile
ENV STARTUPDIR=/dockerstartup
ENV INST_SCRIPTS=$STARTUPDIR/install
ENV DONT_PROMPT_WSL_INSTALL="No_Prompt_please"
WORKDIR $HOME

######### Customize Container Here ###########

# Install Winbox
COPY ./src/install/winbox/install_winbox.sh $INST_SCRIPTS/winbox/
RUN bash $INST_SCRIPTS/winbox/install_winbox.sh  && rm -rf $INST_SCRIPTS/winbox/

COPY ./src/install/winbox/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh && \
    chmod 755 $STARTUPDIR/custom_startup.sh

# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/ && \
    cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png && \
    apt-get remove -y xfce4-panel

######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME=/home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000