ARG LANG=de_DE.UTF-8
ARG LANGUAGE=de_DE:de
ARG LC_ALL=de_DE.UTF-8
ARG TZ=Europe/Berlin
ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
LABEL org.opencontainers.image.authors="DerSni <31524614+DjSni@users.noreply.github.com>"
LABEL org.opencontainers.image.source="https://github.com/DjSni/kasm-images"
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV KASM_RX_HOME $STARTUPDIR/kasmrx
ENV INST_SCRIPTS $STARTUPDIR/install


### Install Stuff
RUN apt-get update && apt-get install -y vlc git tmux nano zip xdotool && apt -y upgrade

### Install Brave
COPY ./src/install/ubuntu/brave $INST_SCRIPTS/brave/
RUN bash $INST_SCRIPTS/brave/install_brave.sh  && rm -rf $INST_SCRIPTS/brave/

### Install Visual Studio Code
COPY ./src/install/ubuntu/vs_code $INST_SCRIPTS/vs_code/
RUN bash $INST_SCRIPTS/vs_code/install_vs_code.sh  && rm -rf $INST_SCRIPTS/vs_code/

### Install Only Office
COPY ./src/install/ubuntu/only_office $INST_SCRIPTS/only_office/
RUN bash $INST_SCRIPTS/only_office/install_only_office.sh  && rm -rf $INST_SCRIPTS/only_office/

### Install Signal
COPY ./src/install/ubuntu/signal $INST_SCRIPTS/signal/
RUN bash $INST_SCRIPTS/signal/install_signal.sh  && rm -rf $INST_SCRIPTS/signal/

### Install OBS Studio
COPY ./src/install/ubuntu/obs $INST_SCRIPTS/obs/
RUN bash $INST_SCRIPTS/obs/install_obs.sh  && rm -rf $INST_SCRIPTS/obs/

### Install Thunderbird
#COPY ./src/install/ubuntu/thunderbird $INST_SCRIPTS/thunderbird/
#RUN bash $INST_SCRIPTS/thunderbird/install_thunderbird.sh  && rm -rf $INST_SCRIPTS/thunderbird/

# Install Gamepad Testing Utils
#COPY ./src/install/ubuntu/gamepad_utils $INST_SCRIPTS/gamepad_utils/
#RUN bash $INST_SCRIPTS/gamepad_utils/install_gamepad_utils.sh  && rm -rf $INST_SCRIPTS/gamepad_utils/

### Install WINE
COPY ./src/install/ubuntu/wine $INST_SCRIPTS/wine/
RUN bash $INST_SCRIPTS/wine/install_wine.sh  && rm -rf $INST_SCRIPTS/wine/

### Install Steam
#COPY ./src/install/ubuntu/steam $INST_SCRIPTS/steam/
#RUN bash $INST_SCRIPTS/steam/install_steam.sh  && rm -rf $INST_SCRIPTS/steam/
#COPY ./src/install/ubuntu/steam/custom_startup.sh $STARTUPDIR/custom_startup.sh
#RUN chmod +x $STARTUPDIR/custom_startup.sh
#RUN chmod 755 $STARTUPDIR/custom_startup.sh

### Install Filezilla
COPY ./src/install/ubuntu/filezilla $INST_SCRIPTS/filezilla/
RUN bash $INST_SCRIPTS/filezilla/install_filezilla.sh  && rm -rf $INST_SCRIPTS/filezilla/
#COPY ./src/install/ubuntu/filezilla/custom_startup.sh $STARTUPDIR/custom_startup.sh
#RUN chmod +x $STARTUPDIR/custom_startup.sh
#RUN chmod 755 $STARTUPDIR/custom_startup.sh

### Install VLC
COPY ./src/install/ubuntu/vlc $INST_SCRIPTS/vlc/
RUN bash $INST_SCRIPTS/vlc/install_vlc.sh  && rm -rf $INST_SCRIPTS/vlc/
#COPY ./src/install/ubuntu/vlc/custom_startup.sh $STARTUPDIR/custom_startup.sh
#RUN chmod +x $STARTUPDIR/custom_startup.sh
#RUN chmod 755 $STARTUPDIR/custom_startup.sh

### Install 1Password
COPY /src/ubuntu/install/1password $INST_SCRIPTS/1password/
RUN bash $INST_SCRIPTS/1password/install_1password.sh  && rm -rf $INST_SCRIPTS/1password/

#ADD ./src/common/scripts $STARTUPDIR
RUN $STARTUPDIR/set_user_permission.sh $HOME

RUN chown 1000:0 $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

CMD ["--tail-log"]
